### ISSUE TITLE
Crash When when continue on campagin map (start of the game) (CrashStack inc)

### ISSUE THREAD

**Issue by lazeras** [lazeras/KaosesTweaks#9]
Game crashes when starting to continue time on campagin map. 
Crash stack:
  at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at TaleWorlds.CampaignSystem.Settlements.TownMarketData.GetCategoryData(ItemCategory itemCategory)
   at TaleWorlds.CampaignSystem.Settlements.TownMarketData.GetPrice(EquipmentElement itemRosterElement, MobileParty tradingParty, Boolean isSelling, PartyBase merchantParty)
   at TaleWorlds.CampaignSystem.Settlements.Town.GetItemPrice(ItemObject item, MobileParty tradingParty, Boolean isSelling)
   at KaosesTweaks.Patches.ProductionOutputPatch.Prefix(ItemObject outputItem, Town town, Workshop workshop, Int32 count, Boolean doNotEffectCapital, Int32& __state) in U:\BannerLord\MyMods\KaosesTweaks\KaosesTweaks\Patches\WorkshopsCampaignBehavior.cs:line 25
   at TaleWorlds.CampaignSystem.CampaignBehaviors.WorkshopsCampaignBehavior.ProduceOutput_Patch2(EquipmentElement outputItem, Town town, Workshop workshop, Int32 count, Boolean doNotEffectCapital)
   at TaleWorlds.CampaignSystem.CampaignBehaviors.WorkshopsCampaignBehavior.DoProduction(Production production, Workshop workshop, Town town)
   at TaleWorlds.CampaignSystem.CampaignBehaviors.WorkshopsCampaignBehavior.RunTownWorkshop(Town townComponent, Workshop workshop, Boolean willBeSold)
   at TaleWorlds.CampaignSystem.CampaignBehaviors.WorkshopsCampaignBehavior.DailyTickTown(Town town)
   at TaleWorlds.CampaignSystem.MbEvent`1.InvokeList(EventHandlerRec`1 list, T t)
   at TaleWorlds.CampaignSystem.CampaignEvents.DailyTickTown(Town town)
   at TaleWorlds.CampaignSystem.CampaignEventDispatcher.DailyTickTown(Town town)
   at TaleWorlds.CampaignSystem.CampaignPeriodicEventManager.PeriodicTicker`1.PeriodicTickSome(Double timeUnitsElapsed)
   at TaleWorlds.CampaignSystem.CampaignPeriodicEventManager.PeriodicDailyTick()
   at TaleWorlds.CampaignSystem.CampaignPeriodicEventManager.TickPeriodicEvents()
   at TaleWorlds.CampaignSystem.Campaign.Tick()
   at TaleWorlds.CampaignSystem.GameState.MapState.OnMapModeTick(Single dt)
   at TaleWorlds.CampaignSystem.GameState.MapState.OnTick(Single dt)
   at TaleWorlds.Core.GameStateManager.OnTick(Single dt)
   at TaleWorlds.Core.Game.OnTick(Single dt)
   at TaleWorlds.Core.GameManagerBase.OnTick(Single dt)
   at TaleWorlds.MountAndBlade.Module.OnApplicationTick_Patch1(Module this, Single dt)

**Comment by lazeras** [comment]
should be fixed in 685d91f8316891c947377ebbc5bc6b0a7e99d3ec
